### ISSUE TITLE
error in sorters.lua

### ISSUE THREAD

**Issue by ghost** [Relintai/Relintais-Enemy-Kooldown-Tracker-WotLK#4]
```
[2022/05/10 22:01:32-334-x1]: Rekt-1.11\data\sorters.lua:130: attempt to index local 'a' (a nil value)
(tail call): ?:
<in C code>: in function `sort'
Rekt-1.11\data\cooldowns.lua:231: in function `SortCDs'
Rekt-1.11\data\cooldowns.lua:30: in function `ReassignCds'
Rekt-1.11\Rekt.lua:375: in function `?'
CallbackHandler-1.0\CallbackHandler-1.0.lua:146: in function <...non\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:146>
<string>:"safecall Dispatcher[1]":4: in function <[string "safecall Dispatcher[1]"]:4>
<in C code>: ?
<string>:"safecall Dispatcher[1]":13: in function `?'
CallbackHandler-1.0\CallbackHandler-1.0.lua:91: in function `Fire'
AceEvent-3.0\AceEvent-3.0.lua:70: in function <...ace\AddOns\Bagnon\libs\AceEvent-3.0\AceEvent-3.0.lua:69>
<in C code>: in function `CameraOrSelectOrMoveStop'
<string>:"CAMERAORSELECTORMOVE":4: in function <[string "CAMERAORSELECTORMOVE"]:1>
```

**Comment by Relintai** [comment]
Hmmm I've seen an error similar to this I think about twice, so I was never able to fix this as I was unable to replicate it.

Does this happen often?

Also what's funny is that this shouldn't happen at all. I looked at the code, and at the moment I suspect it has something to do with some incredibly arcane and dumb lua syntax "cleverness".

I have an idea that might fix this, I'll implement that, hopefully it will fix it for good, even if it happens rarely to you aswell.

**Comment by Relintai** [comment]
Please try https://github.com/Relintai/Relintais-Enemy-Kooldown-Tracker-WotLK/releases/tag/1.11.8 and do tell if it pops up again.

**Comment by ghost** [comment]
just realized this is the wotlk repo, sorry. it happened on 2.4.3.
copy-pasted the fix, no errors so far.
