### ISSUE TITLE
What is the meaning of the colors ?

### ISSUE THREAD

**Issue by flazouh** [Relintai/Relintais-Enemy-Kooldown-Tracker-WotLK#5]

**Comment by Relintai** [comment]
![image](https://user-images.githubusercontent.com/16229538/191379759-e800c432-c293-4d65-9dc6-abade198aa99.png)

**Comment by flazouh** [comment]
I still don't understand, what do the colors mean ? Why is one blue, one is green, and the others red ?

**Comment by Relintai** [comment]
The colors represent the type of the cooldown. On that image red is for burst cds, that light blue is for defensives, blue is for sliences, etc...

If you want to see which cooldown belong to which category you will have to look at this file:

https://github.com/Relintai/Relintais-Enemy-Kooldown-Tracker-WotLK/blob/master/data/spells.lua

lets take a random line:

``` [14177] = {180, nil, 180, 180, 180, 3, "Rogue", "nuke", false, false, false}, --Cold Blood ```

Here the category is nuke, so it will have a red background if you did not change your color settings.

**Comment by flazouh** [comment]
Alright thanks 👍
