### ISSUE TITLE
rekt addon error

### ISSUE THREAD

**Issue by Milo154** [Relintai/Relintais-Enemy-Kooldown-Tracker-WotLK#6]
Hello! I've been using "rekt" addon for a long time and i can say its the best addon for pvp i've seen so far in wotlk. But there is little small error i have every time i log in wow is that i have to type /rekt and disable and enable addon otherwise addon will be showing a column of squares or " empty cooldowns " on my screen, when i disable it and enable addon it cleans my screen. Like this for example 
![image](https://user-images.githubusercontent.com/130801534/232162868-3408527d-cdf3-4a24-8d35-c4349727aef6.png)

**Comment by Relintai** [comment]
Are you using the latest version? This should have been fixed in 1.11.7, so please try to update the addon, and tell me if it still happens after.

https://github.com/Relintai/Relintais-Enemy-Kooldown-Tracker-WotLK/releases

**Comment by Milo154** [comment]
hey Peter!
I think it fixed my problem :D I cant believe it, for so long i didnt care
and every time i would log some char or /reload i would go /rekt enable and
disable addon to turn that off :D and not its finally fixed! Rekt is best
pvp addon i've ever seen! If you have any more addons please recommend me,
thank you so much

**Comment by Relintai** [comment]
Hey!

Nice!

Glad to hear that it worked.

As for other addons I only have this one unfortunately.

Have a Nice Day!

**Comment by Milo154** [comment]
Hello
Sorry for replying here but i have one more question. Can your addon show
cooldown remaining in seconds instead of usual timer?

**Comment by Relintai** [comment]
That is actually handled by other addons like OmniCC.

This addon doesn't put numbers onto the frames at all.

So, the answer is unfortunately no. It can't override the defaults.
